### ISSUE TITLE
Can not do a Voice/Video Call

### ISSUE THREAD

**Issue by Mitezuss** [jhdcruz/Desktop-Messenger#1]
That is the problem.
Maybe need give authorized to google chrome (chromium) use the hardware...

**Comment by jhdcruz** [comment]
Have you tried running it as admin? or maybe restart the app itself.

**Comment by Mitezuss** [comment]
Hi. Yes, i tested all.

Is the call working for you? In a clear Windows? I think the problem is the chrome that need permission and unable to ask.

And cannot accept any call (I can see the incoming, but can not accept)

Edited: `Grammar`

**Comment by jhdcruz** [comment]
It is probably because `Chromium` is waiting for the user to accept the permission, which is on hold since it doesn't appear on the window itself.

P.S 
    - I'm currently investigating it.

Update:
 - `Popups` has been allowed, you can now see the group call being initiated but still denying the permissions. still working...
 - Audio Call is working (for me at least.)
 - It's probably working right now (I don't have a camera/webcam on my computer, but so far it works on the other side and detects audio/cam drivers)

**Comment by jhdcruz** [comment]
Please check-out [v1.1.4](https://github.com/jhdcruz/Desktop-Messenger/releases/tag/1.1.4) and see if it works out for you. (it works out for me, at least)

**Comment by Mitezuss** [comment]
Sorry, i can not test now (problem with my PC). But i will test when i can (video and call).
Thanks you for the fix. And sorry for my bad english =d (is not my language).
